allowBuilds:
  '@fortawesome/fontawesome-free': true
  esbuild: true
  sharp: true
  simple-git-hooks: true
  ttf2woff2: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
  - ttf2woff2
